version: '3'
services:
  web:
    build: .
    command: /bin/sh -c "rm -f tmp/pids/server.pid && rails s -p 8080 -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
    env_file:
      - .env
    ports:
      - 8080:8080
    tty: true
    stdin_open: true
    depends_on:
      - db
    links:
      - db
  db:
    image: mysql:8.0
    volumes:
      - data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: blog_api
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    ports:
      - "3306:3306"
    restart: always
volumes:
  data:
    driver: local
  bundle:
    driver: local
